default: &default
  adapter: mysql2
  encoding: utf8
  pool:  <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= SECRETS['MYSQL_USER'] %>
  password: <%= SECRETS['MYSQL_PASSWORD'] %>

development:
  <<: *default
  host: dockerhost
  port: 3307
  database: kcpv_development

test:
  <<: *default
  host: dockerhost
  port: 3307
  database: kcpv_test

